; Konfigurace simulatoru
; Vice info o ini formatu pro php: https://www.php.net/manual/en/function.parse-ini-file.php

[general]
; verze simulatoru
version = 2.1.0
; verze podporovaneho php
php_version = 7.4

[simulate_sections]
; Kliknuti na nazev sekce simuluje utok nad vsemi eventy v dane sekci a vypise souhrn. Muze zatezovat server.
enabled = "true"
; simuluje kazdy event N-krat a vypise nejhorsi vysledek (aby se zabranilo nahodnym uspechum a hrac si nerozbil armadu)
retries_per_event = 3
