; Konfigurace simulatoru. Vice info o ini formatu pro php: https://www.php.net/manual/en/function.parse-ini-file.php

[general]
; verze simulatoru
version = 3.1.0
; verze podporovaneho php
php_version = 7.4
