<?php

$lang['unit_1'] = array('name'=>'Ozbrojený vesničan', 'desc'=>'');
$lang['unit_2'] = array('name'=>'Kovář', 'desc'=>'');
$lang['unit_3'] = array('name'=>'Vesničan', 'desc'=>'');
$lang['unit_4'] = array('name'=>'Velitel osady', 'desc'=>'');
$lang['unit_5'] = array('name'=>'Katapult', 'desc'=>'');
$lang['unit_6'] = array('name'=>'Osadník s lukem', 'desc'=>'');
$lang['unit_7'] = array('name'=>'Žebrák', 'desc'=>'');
$lang['unit_10'] = array('name'=>'Otrok s kopím', 'desc'=>'');
$lang['unit_11'] = array('name'=>'Otrok s oštěpy', 'desc'=>'');
$lang['unit_12'] = array('name'=>'Otrok štítonoš', 'desc'=>'');
$lang['unit_13'] = array('name'=>'Těžký katapult', 'desc'=>'');
$lang['unit_14'] = array('name'=>'Městská pěchota', 'desc'=>'');
$lang['unit_15'] = array('name'=>'Městští kušníci', 'desc'=>'');
$lang['unit_16'] = array('name'=>'Starostova ochranka', 'desc'=>'');
$lang['unit_17'] = array('name'=>'Starosta', 'desc'=>'');
$lang['unit_18'] = array('name'=>'Balista', 'desc'=>'');
$lang['unit_19'] = array('name'=>'Těžká balista', 'desc'=>'');
$lang['unit_20'] = array('name'=>'Místodržící', 'desc'=>'');
$lang['unit_21'] = array('name'=>'Odpadlík', 'desc'=>'');
$lang['unit_22'] = array('name'=>'Renegád', 'desc'=>'');
$lang['unit_23'] = array('name'=>'Master Lovec', 'desc'=>'');
$lang['unit_24'] = array('name'=>'Potulný Kouzelník', 'desc'=>'');
$lang['unit_25'] = array('name'=>'Archeolog', 'desc'=>'');
$lang['unit_26'] = array('name'=>'Starý Archeolog', 'desc'=>'');
$lang['unit_27'] = array('name'=>'Voják předsunuté hlídky', 'desc'=>'');
$lang['unit_28'] = array('name'=>'Otrokář', 'desc'=>'');

$lang['unit_100'] = array('name'=>'Elfí lučištník', 'desc'=>'');
$lang['unit_101'] = array('name'=>'Elfí elitní lučištník', 'desc'=>'');
$lang['unit_105'] = array('name'=>'Elfí kopijník', 'desc'=>'');
$lang['unit_106'] = array('name'=>'Elfí kopijník na obřím pavoukovi', 'desc'=>'');
$lang['unit_110'] = array('name'=>'Druid', 'desc'=>'');
$lang['unit_111'] = array('name'=>'Veledruid', 'desc'=>'');
$lang['unit_112'] = array('name'=>'Zelený lesní pavouk', 'desc'=>'');
$lang['unit_113'] = array('name'=>'Červený lesní pavouk', 'desc'=>'');
$lang['unit_114'] = array('name'=>'Černý lesní pavouk', 'desc'=>'');
$lang['unit_115'] = array('name'=>'Zlatý lesní pavouk', 'desc'=>'');
$lang['unit_116'] = array('name'=>'Obří zelený pavouk', 'desc'=>'');
$lang['unit_117'] = array('name'=>'Obří červený pavouk', 'desc'=>'');
$lang['unit_118'] = array('name'=>'Obří černý pavouk', 'desc'=>'');
$lang['unit_120'] = array('name'=>'Lesní obr', 'desc'=>'');
$lang['unit_121'] = array('name'=>'Lesní Bizon', 'desc'=>'');
$lang['unit_122'] = array('name'=>'Lesní Troll', 'desc'=>'');
$lang['unit_123'] = array('name'=>'Horský obr', 'desc'=>'');
$lang['unit_124'] = array('name'=>'Prastarý Horský obr', 'desc'=>'');
$lang['unit_125'] = array('name'=>'Prastarý Lesní Troll', 'desc'=>'');
$lang['unit_130'] = array('name'=>'Wurm', 'desc'=>'');
$lang['unit_131'] = array('name'=>'Lesní obr jezdící na Posvátném Wurmovi', 'desc'=>'');
$lang['unit_132'] = array('name'=>'Horský Wurm', 'desc'=>'');
$lang['unit_133'] = array('name'=>'Prastarý Horský Wurm', 'desc'=>'');
$lang['unit_135'] = array('name'=>'Jednorožec', 'desc'=>'');
$lang['unit_136'] = array('name'=>'Posvátný jednorožec', 'desc'=>'');
$lang['unit_190'] = array('name'=>'Ent', 'desc'=>'');
$lang['unit_191'] = array('name'=>'Starodávný Ent', 'desc'=>'');
$lang['unit_192'] = array('name'=>'Bílý pavouk', 'desc'=>'');
$lang['unit_193'] = array('name'=>'Elfí hraničář', 'desc'=>'');

$lang['unit_200'] = array('name'=>'Vyznavač boha ledu', 'desc'=>'');
$lang['unit_201'] = array('name'=>'Zasvěcenec boha ledu', 'desc'=>'');
$lang['unit_202'] = array('name'=>'Æthrův věrný', 'desc'=>'');
$lang['unit_203'] = array('name'=>'Akolyta boha ledu', 'desc'=>'');
$lang['unit_210'] = array('name'=>'Ledový Přízrak', 'desc'=>'');
$lang['unit_211'] = array('name'=>'Starodávný Ledový Přízrak', 'desc'=>'');
$lang['unit_212'] = array('name'=>'Ledový Elementál', 'desc'=>'');
$lang['unit_214'] = array('name'=>'Ledový válečník', 'desc'=>'');
$lang['unit_215'] = array('name'=>'Sestra Ledu', 'desc'=>'');
$lang['unit_220'] = array('name'=>'Ledový obr', 'desc'=>'');
$lang['unit_221'] = array('name'=>'Starodávný ledový obr', 'desc'=>'');
$lang['unit_222'] = array('name'=>'Šaman Ledu', 'desc'=>'');
$lang['unit_223'] = array('name'=>'Æthrův šaman Ledu', 'desc'=>'');
$lang['unit_230'] = array('name'=>'Ledová hydra', 'desc'=>'');
$lang['unit_231'] = array('name'=>'Starodávná ledová hydra', 'desc'=>'');
$lang['unit_232'] = array('name'=>'Ledová hvězda', 'desc'=>'');
$lang['unit_233'] = array('name'=>'Æthrova ledová hvězda', 'desc'=>'');
$lang['unit_290'] = array('name'=>'Æthrův ledový válečník', 'desc'=>'');
$lang['unit_291'] = array('name'=>'Mág ledu', 'desc'=>'');
$lang['unit_292'] = array('name'=>'Ledová hradba', 'desc'=>'');
$lang['unit_293'] = array('name'=>'Velemág Ledu', 'desc'=>'');
$lang['unit_294'] = array('name'=>'Snežný obr', 'desc'=>'');
$lang['unit_295'] = array('name'=>'Sněžný vlk', 'desc'=>'');
$lang['unit_296'] = array('name'=>'Ledový vlk', 'desc'=>'');

$lang['unit_300'] = array('name'=>'Oživlé bahno', 'desc'=>'');
$lang['unit_301'] = array('name'=>'Toxické oživlé bahno', 'desc'=>'');
$lang['unit_305'] = array('name'=>'Kamenný Válečník', 'desc'=>'');
$lang['unit_306'] = array('name'=>'Mramorový Válečník', 'desc'=>'');
$lang['unit_307'] = array('name'=>'Onyxový Válečník', 'desc'=>'');
$lang['unit_308'] = array('name'=>'Topázový Válečník', 'desc'=>'');
$lang['unit_310'] = array('name'=>'Kamenný Golem', 'desc'=>'');
$lang['unit_311'] = array('name'=>'Mramorový Golem', 'desc'=>'');
$lang['unit_312'] = array('name'=>'Onyxový Golem', 'desc'=>'');
$lang['unit_313'] = array('name'=>'Topázový Golem', 'desc'=>'');
$lang['unit_315'] = array('name'=>'Bahenní Ještěr', 'desc'=>'');
$lang['unit_316'] = array('name'=>'Toxický Bahenní Ještěr', 'desc'=>'');
$lang['unit_320'] = array('name'=>'Kamenožrout', 'desc'=>'');
$lang['unit_321'] = array('name'=>'Mramorožrout', 'desc'=>'');
$lang['unit_322'] = array('name'=>'Onyxožrout', 'desc'=>'');
$lang['unit_323'] = array('name'=>'Topazožrout', 'desc'=>'');
$lang['unit_325'] = array('name'=>'Minotaurus', 'desc'=>'');
$lang['unit_326'] = array('name'=>'Toxický Minotaurus', 'desc'=>'');
$lang['unit_330'] = array('name'=>'Mág země', 'desc'=>'');
$lang['unit_331'] = array('name'=>'Velemág země', 'desc'=>'');
$lang['unit_335'] = array('name'=>'Bahenní Had', 'desc'=>'');
$lang['unit_336'] = array('name'=>'Toxický Bahenní Had', 'desc'=>'');
$lang['unit_390'] = array('name'=>'Kamenný Kraken', 'desc'=>'');
$lang['unit_391'] = array('name'=>'Bahenní Ještěr s kuší', 'desc'=>'');
$lang['unit_392'] = array('name'=>'Toxický Bahenní Ještěr s kuší', 'desc'=>'');

$lang['unit_410'] = array('name'=>'Inkvizitor', 'desc'=>'');
$lang['unit_420'] = array('name'=>'Exorcista', 'desc'=>'');
$lang['unit_430'] = array('name'=>'Paladin Světla', 'desc'=>'');

$lang['unit_1000'] = array('name'=>'Zombie', 'desc'=>'');
$lang['unit_1001'] = array('name'=>'NIC', 'desc'=>'');
$lang['unit_1002'] = array('name'=>'Dreaddův přívrženec', 'desc'=>'');
$lang['unit_1010'] = array('name'=>'Lich', 'desc'=>'');
$lang['unit_1011'] = array('name'=>'Arcilich', 'desc'=>'');
$lang['unit_1012'] = array('name'=>'Prokletý kněz', 'desc'=>'');
$lang['unit_1013'] = array('name'=>'Prokletý kněz věčné Temnoty', 'desc'=>'');
$lang['unit_1020'] = array('name'=>'Stín', 'desc'=>'');
$lang['unit_1021'] = array('name'=>'NIC', 'desc'=>'');
$lang['unit_1022'] = array('name'=>'NIC', 'desc'=>'');
$lang['unit_1023'] = array('name'=>'Černý rytíř', 'desc'=>'');
$lang['unit_1024'] = array('name'=>'Temný rytíř', 'desc'=>'');
$lang['unit_1025'] = array('name'=>'Rytíř věčné Temnoty', 'desc'=>'');
$lang['unit_1030'] = array('name'=>'Temný přízrak', 'desc'=>'');
$lang['unit_1032'] = array('name'=>'Soulkeeper', 'desc'=>'');
$lang['unit_1033'] = array('name'=>'Soulkeeper věčné Temnoty', 'desc'=>'');
$lang['unit_1034'] = array('name'=>'Nekromant', 'desc'=>'');
$lang['unit_1089'] = array('name'=>'Upír', 'desc'=>'');
$lang['unit_1090'] = array('name'=>'Kostlivec', 'desc'=>'');
$lang['unit_1091'] = array('name'=>'Dreaddův Vyvolený', 'desc'=>'');
$lang['unit_1092'] = array('name'=>'Uvězněná duše', 'desc'=>'');
$lang['unit_1093'] = array('name'=>'Nemrtvý Druid', 'desc'=>'');
$lang['unit_1094'] = array('name'=>'Nemrtvý ohnivý kouzelník', 'desc'=>'');
$lang['unit_1095'] = array('name'=>'Nemrtvý ledový kouzelník', 'desc'=>'');
$lang['unit_1096'] = array('name'=>'Zvěstovatel soudného dne', 'desc'=>'');
$lang['unit_1097'] = array('name'=>'Obří kostlivec', 'desc'=>'');
$lang['unit_1098'] = array('name'=>'Prokletý ent', 'desc'=>'');
$lang['unit_1099'] = array('name'=>'Ghúl', 'desc'=>'');

$lang['unit_1100'] = array('name'=>'Mág ohně', 'desc'=>'');
$lang['unit_1101'] = array('name'=>'Arcimág ohně', 'desc'=>'');
$lang['unit_1105'] = array('name'=>'Stínový medvěd', 'desc'=>'');
$lang['unit_1106'] = array('name'=>'Stínový ohnivý medvěd', 'desc'=>'');
$lang['unit_1110'] = array('name'=>'Ohnivý golem', 'desc'=>'');
$lang['unit_1111'] = array('name'=>'Lávový golem', 'desc'=>'');
$lang['unit_1112'] = array('name'=>'Magmatický golem', 'desc'=>'');
$lang['unit_1115'] = array('name'=>'Stínová valkýra', 'desc'=>'');
$lang['unit_1116'] = array('name'=>'Stínová ohnivá valkýra', 'desc'=>'');
$lang['unit_1120'] = array('name'=>'Ohnivý Fénix', 'desc'=>'');
$lang['unit_1121'] = array('name'=>'Ledový Fénix', 'desc'=>'');
$lang['unit_1122'] = array('name'=>'Anděl věčného ohně', 'desc'=>'');
$lang['unit_1125'] = array('name'=>'Stínový mág', 'desc'=>'');
$lang['unit_1126'] = array('name'=>'Stínový arcimág', 'desc'=>'');
$lang['unit_1130'] = array('name'=>'Flamekeeper', 'desc'=>'');
$lang['unit_1135'] = array('name'=>'Stínový drak', 'desc'=>'');
$lang['unit_1136'] = array('name'=>'Stínový ohnivý drak', 'desc'=>'');
$lang['unit_1190'] = array('name'=>'Ohnivý Služebník', 'desc'=>'');
$lang['unit_1191'] = array('name'=>'Efreet', 'desc'=>'');
$lang['unit_1192'] = array('name'=>'Flamekeeper Lord', 'desc'=>'');
$lang['unit_1193'] = array('name'=>'Magmatický Obr', 'desc'=>'');
$lang['unit_1194'] = array('name'=>'Stínový ohař', 'desc'=>'');
$lang['unit_1195'] = array('name'=>'Stínová bestie', 'desc'=>'');
$lang['unit_1196'] = array('name'=>'Akolyta věčného ohně', 'desc'=>'');
$lang['unit_1197'] = array('name'=>'Efreet šaman', 'desc'=>'');
$lang['unit_1198'] = array('name'=>'Stínový Efreet', 'desc'=>'');

$lang['unit_1202'] = array('name'=>'Temný Elf', 'desc'=>'');
$lang['unit_1203'] = array('name'=>'Velitel Temných Elfů', 'desc'=>'');

$lang['unit_2000'] = array('name'=>'Goblin', 'desc'=>'');
$lang['unit_2001'] = array('name'=>'Goblin s Prakem', 'desc'=>'');
$lang['unit_2005'] = array('name'=>'Hobgoblin', 'desc'=>'');
$lang['unit_2010'] = array('name'=>'Goblin Fanatik', 'desc'=>'');
$lang['unit_2011'] = array('name'=>'Gobliní pojízdná bomba', 'desc'=>'');
$lang['unit_2015'] = array('name'=>'Goblin na vlkovi', 'desc'=>'');
$lang['unit_2016'] = array('name'=>'Goblin na medvědovi', 'desc'=>'');
$lang['unit_2017'] = array('name'=>'Pán šelem', 'desc'=>'');
$lang['unit_2020'] = array('name'=>'Goblin Pyroman', 'desc'=>'');
$lang['unit_2025'] = array('name'=>'Zlobr', 'desc'=>'');
$lang['unit_2030'] = array('name'=>'Gobliní Vzducholoď', 'desc'=>'');
$lang['unit_2031'] = array('name'=>'Goblin Paragán', 'desc'=>'');
$lang['unit_2032'] = array('name'=>'Gobliní Exterminátor', 'desc'=>'');
$lang['unit_2033'] = array('name'=>'Gobliní Sabotér', 'desc'=>'');
$lang['unit_2034'] = array('name'=>'Gobliní Hrdina', 'desc'=>'');
$lang['unit_2035'] = array('name'=>'Gobliní Patriarcha', 'desc'=>'');
$lang['unit_2036'] = array('name'=>'Gobliní Hybridní Vzducholoď', 'desc'=>'');
$lang['unit_2037'] = array('name'=>'Gobliní Vyztužená Vzducholoď', 'desc'=>'');

$lang['unit_2100'] = array('name'=>'Vlkodlak', 'desc'=>'');
$lang['unit_2101'] = array('name'=>'Sněhobílý Vlkodlak', 'desc'=>'');
$lang['unit_2102'] = array('name'=>'Kancodlak', 'desc'=>'');
$lang['unit_2103'] = array('name'=>'Sněhobílý Kancodlak', 'desc'=>'');
$lang['unit_2104'] = array('name'=>'Medvědodlak', 'desc'=>'');
$lang['unit_2105'] = array('name'=>'Sněhobílý Mědvědodlak', 'desc'=>'');
$lang['unit_2110'] = array('name'=>'Mamutodlak', 'desc'=>'');
$lang['unit_2111'] = array('name'=>'Sněhobílý Mamutodlak', 'desc'=>'');

$lang['unit_2292'] = array('name'=>'Vrchní kněžka Enakra', 'desc'=>'');
$lang['unit_2293'] = array('name'=>'Ardor strážce Enakry', 'desc'=>'');

$lang['unit_2300'] = array('name'=>'Válečník', 'desc'=>'');
$lang['unit_2302'] = array('name'=>'Svatý válečník', 'desc'=>'');
$lang['unit_2310'] = array('name'=>'Střelec', 'desc'=>'');
$lang['unit_2312'] = array('name'=>'Elitní střelec', 'desc'=>'');
$lang['unit_2320'] = array('name'=>'Mnich', 'desc'=>'');
$lang['unit_2322'] = array('name'=>'Zasvěcenec světla', 'desc'=>'');
$lang['unit_2330'] = array('name'=>'Křižák', 'desc'=>'');
$lang['unit_2332'] = array('name'=>'Paladin', 'desc'=>'');
$lang['unit_2390'] = array('name'=>'Světlonoš', 'desc'=>'');

$lang['unit_2400'] = array('name'=>'Ascendancin válečník', 'desc'=>'');
$lang['unit_2410'] = array('name'=>'Klerik', 'desc'=>'');
$lang['unit_2420'] = array('name'=>'Převor', 'desc'=>'');
$lang['unit_2430'] = array('name'=>'Preascended', 'desc'=>'');
$lang['unit_2490'] = array('name'=>'Ascended', 'desc'=>'');

$lang['unit_3000'] = array('name'=>'Barbar', 'desc'=>'');
$lang['unit_3001'] = array('name'=>'Náčelník barbarů', 'desc'=>'');
$lang['unit_3002'] = array('name'=>'Barbar na koni', 'desc'=>'');
$lang['unit_3003'] = array('name'=>'Barbar lučištník', 'desc'=>'');
$lang['unit_3010'] = array('name'=>'Trpaslík se sekerou', 'desc'=>'');
$lang['unit_3011'] = array('name'=>'Trpaslík s kuší', 'desc'=>'');
$lang['unit_3012'] = array('name'=>'Trpaslík kapitán', 'desc'=>'');
$lang['unit_3013'] = array('name'=>'Trpaslík těžké pěchoty', 'desc'=>'');
$lang['unit_3014'] = array('name'=>'Trpasličí legionář', 'desc'=>'');
$lang['unit_3015'] = array('name'=>'Trpaslík', 'desc'=>'');
$lang['unit_3016'] = array('name'=>'Trpasličí past', 'desc'=>'');
$lang['unit_3017'] = array('name'=>'Elitní trpaslík s kuší', 'desc'=>'');
$lang['unit_3018'] = array('name'=>'Trpasličí opevnění', 'desc'=>'');
$lang['unit_3020'] = array('name'=>'Bandita', 'desc'=>'');
$lang['unit_3021'] = array('name'=>'Bandita s lukem', 'desc'=>'');
$lang['unit_3022'] = array('name'=>'Bandita velitel', 'desc'=>'');
$lang['unit_3030'] = array('name'=>'Gnóm s kuší', 'desc'=>'');
$lang['unit_3031'] = array('name'=>'Osedlaný Mamut s Gnomí Posádkou', 'desc'=>'');
$lang['unit_3040'] = array('name'=>'Obr lidožrout', 'desc'=>'');
$lang['unit_3041'] = array('name'=>'Prokletý Obr', 'desc'=>'');
$lang['unit_3042'] = array('name'=>'Hnijící Nemrtvý Obr', 'desc'=>'');
$lang['unit_3043'] = array('name'=>'Ohnivý Obr', 'desc'=>'');
$lang['unit_3044'] = array('name'=>'Kamenný Obr', 'desc'=>'');

$lang['unit_3100'] = array('name'=>'Nižší ohnivý splozenec', 'desc'=>'');

$lang['unit_3200'] = array('name'=>'Pěšák starého impéria', 'desc'=>'');
$lang['unit_3201'] = array('name'=>'Kapitán pěšáků starého impéria', 'desc'=>'');
$lang['unit_3202'] = array('name'=>'Plukovník pěšáků starého impéria', 'desc'=>'');
$lang['unit_3210'] = array('name'=>'Těžký pěšák starého impéria', 'desc'=>'');
$lang['unit_3211'] = array('name'=>'Kapitán těžkých pěšáků starého impéria', 'desc'=>'');
$lang['unit_3212'] = array('name'=>'Plukovník těžkých pěšáků starého impéria', 'desc'=>'');
$lang['unit_3220'] = array('name'=>'Rytíř starého impéria', 'desc'=>'');
$lang['unit_3221'] = array('name'=>'Kapitán rytířů starého impéria', 'desc'=>'');
$lang['unit_3230'] = array('name'=>'Generál starého impéria', 'desc'=>'');
$lang['unit_3240'] = array('name'=>'Střelec starého impéria', 'desc'=>'');
$lang['unit_3241'] = array('name'=>'Kapitán střelců starého impéria', 'desc'=>'');
$lang['unit_3242'] = array('name'=>'Elitní střelec starého impéria', 'desc'=>'');
$lang['unit_3243'] = array('name'=>'Kapitán elitních střelců starého impéria', 'desc'=>'');
$lang['unit_3250'] = array('name'=>'Král Therysus', 'desc'=>'');
$lang['unit_3251'] = array('name'=>'Therysusova elitní stráž', 'desc'=>'');

$lang['unit_3300'] = array('name'=>'Medůza', 'desc'=>'');
$lang['unit_3301'] = array('name'=>'Kamenná socha', 'desc'=>'');
$lang['unit_3302'] = array('name'=>'Není', 'desc'=>'');
$lang['unit_3340'] = array('name'=>'Bažinný ent', 'desc'=>'');

$lang['unit_3400'] = array('name'=>'Dehinator', 'desc'=>'');
$lang['unit_3401'] = array('name'=>'Zeď Temné pevnosti', 'desc'=>'');
$lang['unit_3402'] = array('name'=>'Prokletý Mág', 'desc'=>'');
$lang['unit_3403'] = array('name'=>'Prokletý válečník', 'desc'=>'');
$lang['unit_3404'] = array('name'=>'Dehinatorova ochranka', 'desc'=>'');
$lang['unit_3410'] = array('name'=>'Ledový král', 'desc'=>'');
$lang['unit_3411'] = array('name'=>'Ledový král', 'desc'=>'');
$lang['unit_3419'] = array('name'=>'Zeď pokrytá slizem', 'desc'=>'');
$lang['unit_3420'] = array('name'=>'Mucus, král Toxických elementálů', 'desc'=>'');

$lang['unit_3500'] = array('name'=>'Královna Medůz', 'desc'=>'');
$lang['unit_3501'] = array('name'=>'Temný mág', 'desc'=>'');
$lang['unit_3502'] = array('name'=>'Vyšší Temný Mág', 'desc'=>'');
$lang['unit_3503'] = array('name'=>'Zeď Prokleté citadely', 'desc'=>'');
$lang['unit_3517'] = array('name'=>'Černý vlk', 'desc'=>'');
$lang['unit_3518'] = array('name'=>'Šedý vlk', 'desc'=>'');
$lang['unit_3519'] = array('name'=>'Stínový lovec', 'desc'=>'');
$lang['unit_3520'] = array('name'=>'Král vlk', 'desc'=>'');
$lang['unit_3521'] = array('name'=>'Duch vlka', 'desc'=>'');

$lang['unit_3600'] = array('name'=>'Eternan vyvolávač', 'desc'=>'');
$lang['unit_3601'] = array('name'=>'Eternan mág', 'desc'=>'');
$lang['unit_3602'] = array('name'=>'Eternan dohlížitel', 'desc'=>'');
$lang['unit_3630'] = array('name'=>'Energetický služebník', 'desc'=>'');

$lang['unit_3700'] = array('name'=>'Zmutovaný Wurm', 'desc'=>'');

$lang['unit_3800'] = array('name'=>'Padlý válečník', 'desc'=>'');

$lang['unit_3900'] = array('name'=>'Ohnivý Elementál', 'desc'=>'');
$lang['unit_3901'] = array('name'=>'Vzdušný Elementál', 'desc'=>'');
$lang['unit_3902'] = array('name'=>'Vodní Elementál', 'desc'=>'');
$lang['unit_3903'] = array('name'=>'Zemní Elementál', 'desc'=>'');
$lang['unit_3910'] = array('name'=>'Toxický Elementál Obránce', 'desc'=>'');
$lang['unit_3911'] = array('name'=>'Toxický Elementál Útočník', 'desc'=>'');
$lang['unit_3912'] = array('name'=>'Toxická Elementární Bublina', 'desc'=>'');
$lang['unit_3950'] = array('name'=>'Hnijící vesničan', 'desc'=>'');

$lang['unit_4000'] = array('name'=>'Meteorit', 'desc'=>'');
$lang['unit_4001'] = array('name'=>'Ohnivá koule', 'desc'=>'');
$lang['unit_4002'] = array('name'=>'Ledová koule', 'desc'=>'');
$lang['unit_4003'] = array('name'=>'Rozžhavené magma', 'desc'=>'');
$lang['unit_4003'] = array('name'=>'Ohnivý déšť', 'desc'=>'');

$lang['unit_4100'] = array('name'=>'Kamenná hradba', 'desc'=>'');
$lang['unit_4101'] = array('name'=>'Kamenná věž', 'desc'=>'');
$lang['unit_4102'] = array('name'=>'Věž s balistou', 'desc'=>'');

$lang['unit_5000'] = array('name'=>'Ohnivý démon', 'desc'=>'');
$lang['unit_5001'] = array('name'=>'Plamenný démon', 'desc'=>'');
$lang['unit_5002'] = array('name'=>'Plamenný démon s bičem', 'desc'=>'');
$lang['unit_5003'] = array('name'=>'Plamenný démon mág', 'desc'=>'');
$lang['unit_5004'] = array('name'=>'Plamenný démon arcimág', 'desc'=>'');
$lang['unit_5010'] = array('name'=>'Následovník démonů - Lidský Odpadlík', 'desc'=>'');
$lang['unit_5011'] = array('name'=>'Následovník démonů - Zasvěcenec', 'desc'=>'');
$lang['unit_5012'] = array('name'=>'Následovník démonů - Vyšší Zasvěcenec', 'desc'=>'');
$lang['unit_5013'] = array('name'=>'Následovník démonů - Berzeker', 'desc'=>'');
$lang['unit_5014'] = array('name'=>'Následovník démonů - Kacíř', 'desc'=>'');
$lang['unit_5015'] = array('name'=>'Následovník démonů - Prokletý Berzeker', 'desc'=>'');
$lang['unit_5020'] = array('name'=>'Démon Jezdec', 'desc'=>'');
$lang['unit_5021'] = array('name'=>'Démon Těžký Jezdec', 'desc'=>'');
$lang['unit_5030'] = array('name'=>'Démon Křižák', 'desc'=>'');
$lang['unit_5031'] = array('name'=>'Démon Těžký Křižák', 'desc'=>'');
$lang['unit_5032'] = array('name'=>'Démon Válečník Temnoty', 'desc'=>'');
$lang['unit_5033'] = array('name'=>'Démon Bojový Mág Temnoty', 'desc'=>'');
$lang['unit_5040'] = array('name'=>'Démon Kněz Krvavého Měsíce', 'desc'=>'');
$lang['unit_5041'] = array('name'=>'Démon Mág Krvavého Měsíce', 'desc'=>'');
$lang['unit_5050'] = array('name'=>'Ohnivý imp', 'desc'=>'');
$lang['unit_5060'] = array('name'=>'Stínový válečník', 'desc'=>'');
$lang['unit_5062'] = array('name'=>'Stínový mág', 'desc'=>'');
$lang['unit_5064'] = array('name'=>'Stínový jezdec', 'desc'=>'');
$lang['unit_5065'] = array('name'=>'Stínový obrněný jezdec', 'desc'=>'');
$lang['unit_5066'] = array('name'=>'Stínový obr', 'desc'=>'');

$lang['unit_5100'] = array('name'=>'Ohnivý přízrak', 'desc'=>'');

$lang['unit_5500'] = array('name'=>'Temný Lord Argon', 'desc'=>'');
$lang['unit_5501'] = array('name'=>'Dh Atrog řečený Válečník', 'desc'=>'');
$lang['unit_5502'] = array('name'=>'Dh Ratu řečený Posel ohně', 'desc'=>'');
$lang['unit_5503'] = array('name'=>'Dh Tog řečený Mág ohně', 'desc'=>'');
$lang['unit_5504'] = array('name'=>'Dh Atog řečený sběratel soch', 'desc'=>'');
$lang['unit_5505'] = array('name'=>'Ragnarokk, prokletý wurm', 'desc'=>'');
$lang['unit_5506'] = array('name'=>'Rah Atrog řečený Vyvolávač', 'desc'=>'');
$lang['unit_5507'] = array('name'=>'Anděl z Temnoty', 'desc'=>'');
$lang['unit_5550'] = array('name'=>'Ohnivý přízrak', 'desc'=>'');

$lang['unit_6000'] = array('name'=>'Agranat, řečený zloděj duší', 'desc'=>'');

$lang['unit_9000'] = array('name'=>'Velikonoční králíček', 'desc'=>'');
$lang['unit_9001'] = array('name'=>'Agresivní velikonoční kuřátko', 'desc'=>'');
$lang['unit_9002'] = array('name'=>'Nepoužitelný golem', 'desc'=>'');
$lang['unit_9003'] = array('name'=>'Skoropoužitelný golem', 'desc'=>'');
$lang['unit_9004'] = array('name'=>'Multinefunkční golem', 'desc'=>'');
$lang['unit_9005'] = array('name'=>'Neporazitelný válečník', 'desc'=>'');
$lang['unit_9006'] = array('name'=>'Růžové prasátko', 'desc'=>'');
$lang['unit_9007'] = array('name'=>'Sob, terrorista', 'desc'=>'');
$lang['unit_9008'] = array('name'=>'Sob, bojovník za práva sobů', 'desc'=>'');
$lang['unit_9009'] = array('name'=>'Sob, velitel sobího oddílu', 'desc'=>'');
$lang['unit_9010'] = array('name'=>'Červený gumový medvídek', 'desc'=>'');
$lang['unit_9011'] = array('name'=>'Zelený gumový medvídek', 'desc'=>'');
$lang['unit_9012'] = array('name'=>'Žlutý gumový medvídek', 'desc'=>'');
$lang['unit_9013'] = array('name'=>'Kyselý pavouk', 'desc'=>'');
$lang['unit_9014'] = array('name'=>'Kyselý červík', 'desc'=>'');
$lang['unit_9015'] = array('name'=>'Kapitán Gummibärchen', 'desc'=>'');

$lang['unit_9100'] = array('name'=>'Železnej golem', 'desc'=>'');
$lang['unit_9101'] = array('name'=>'Železnej pavouček', 'desc'=>'');
$lang['unit_9102'] = array('name'=>'Poloautomatická socha', 'desc'=>'');
$lang['unit_9103'] = array('name'=>'Recyklovanej kočkodlak', 'desc'=>'');
$lang['unit_9104'] = array('name'=>'Obrněnej válečnej vůz', 'desc'=>'');
$lang['unit_9105'] = array('name'=>'Železnej býk', 'desc'=>'');
$lang['unit_9120'] = array('name'=>'Železnej škorpion', 'desc'=>'');
$lang['unit_9121'] = array('name'=>'Kamennej chrlič', 'desc'=>'');
$lang['unit_9122'] = array('name'=>'Železnej kněz', 'desc'=>'');
$lang['unit_9130'] = array('name'=>'Obrněnej vrhač oštěpů', 'desc'=>'');
$lang['unit_9140'] = array('name'=>'Železnej orel - prototyp jedna', 'desc'=>'');
$lang['unit_9150'] = array('name'=>'Colosus z temné ocele', 'desc'=>'');
